# This scripts plot EHH decay curve generated by the program selscan. input required for this script is the EHH.out as it is.
# Load the ggplot2 library
library(ggplot2)

# Read the data from the file
# Ensure files are of the correct name and directory
pop1 <- read.table("EHH_popA.out", header = TRUE, sep = "\t") 
pop2 <- read.table("EHH_popB.out", header = TRUE, sep = "\t")

# Assign column names to the dataframe
colnames(pop1) <- c("PDist", "Dist", "Der", "Anc", "EHH")
colnames(pop2) <- c("PDist", "Dist", "Der", "Anc", "EHH")

# Create a line plot with EHH from popA and popB
ggplot() +
  geom_line(data = pop1, aes(x = PDist, y = Der, color = "popA"), linewidth = 1.2) + ## Change as necessary, replace "Der" with "Anc" to plot on Ancestral Allele EHH
  geom_line(data = pop2, aes(x = PDist, y = Der, color = "popB"), linewidth = 1.2) + ## Change as necessary, replace "Der" with "Anc" to plot on Ancestral Allele EHH
  scale_color_manual(values = c("popB" = "red", "popA" = "blue")) +
  labs(x = "Distance from top SNP (mb)", y = "EHH", color = "Population") +
  labs(title = "EHH Curve of SNP XXX Derived Allele in popA and popB") +
  theme_classic()